CREATE TABLE Pessoa(
	CC INT NOT NULL PRIMARY KEY,
	Nome VARCHAR(32) NOT NULL,
	Morada VARCHAR(256) NOT NULL,
	DataNascimento DATE NOT NULL,
);

CREATE TABLE Professor(
	CC INT NOT NULL PRIMARY KEY REFERENCES Pessoa(CC),
	ContactoTelefonico INT NOT NULL,
	Email VARCHAR(32) NOT NULL,
	NumeroFuncionario VARCHAR(32) NOT NULL, 
);

CREATE TABLE Responsavel(
	CC INT NOT NULL PRIMARY KEY REFERENCES Pessoa(CC),
	ContactoTelefonico INT NOT NULL,
	Email VARCHAR(32) NOT NULL,
	RelacaoAluno VARCHAR(32) NOT NULL, 
);

CREATE TABLE PessoaAutorizada(
	CC INT NOT NULL PRIMARY KEY REFERENCES Responsavel(CC),
);

CREATE TABLE EE(
	CC INT NOT NULL PRIMARY KEY REFERENCES Responsavel(CC),
);

CREATE TABLE Aluno(
	CC INT NOT NULL PRIMARY KEY REFERENCES Pessoa(CC),
);

CREATE TABLE AlunoEE(
	CCAluno INT NOT NULL FOREIGN KEY REFERENCES Aluno(CC),
	CCEE INT NOT NULL FOREIGN KEY REFERENCES EE(CC),
	PRIMARY KEY(CCAluno, CCEE),
);

CREATE TABLE Levantar(
	CCAluno INT NOT NULL FOREIGN KEY REFERENCES Aluno(CC),
	CCEE INT NOT NULL FOREIGN KEY REFERENCES EE(CC),
	CCPA INT FOREIGN KEY REFERENCES PessoaAutorizada(CC),
	PRIMARY KEY(CCAluno, CCEE),
);

CREATE TABLE Atividade(
	ID INT NOT NULL PRIMARY KEY,
	Custo FLOAT NOT NULL,
	Designacao VARCHAR(64),
	CCAluno INT NOT NULL FOREIGN KEY REFERENCES Aluno(CC),
);

CREATE TABLE Turma(
	ID INT NOT NULL PRIMARY KEY,
	NumeroMaximoAlunos INT NOT NULL,
	Designacao VARCHAR(32) NOT NULL,
	AnoLetivo INT NOT NULL,
	CCAluno INT NOT NULL FOREIGN KEY REFERENCES Aluno(CC),
);

CREATE TABLE TurmaAtividade(
	IDTurma INT NOT NULL FOREIGN KEY REFERENCES Turma(ID),
	IDAtividade INT NOT NULL FOREIGN KEY REFERENCES Atividade(ID),
	PRIMARY KEY(IDTurma, IDAtividade),
); 

CREATE TABLE ATL(
	ID INT NOT NULL PRIMARY KEY,
	Turma INT NOT NULL FOREIGN KEY REFERENCES Turma(ID),
);